[hostname]
ssh_only = true

[gcloud]
disabled = true

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "gke_algoan-preprod_europe-west1-c_algoan-preprod", context_alias = "preprod", style = "bold bright-green", symbol = "⛵ " },
  { context_pattern = "gke_algoan-prod_europe-west1-c_algoan-prod", context_alias = "prod", style = "bold bright-red", symbol = "🚢 " }
]
